#ifndef FZ_CONFIG_H
#define FZ_CONFIG_H

#define TEMP_ADC_MAX 4095.0f
#define TEMP_R_PULLUP_OHM 1000.0f

#define TEMP_ADC_SHORT_THRESHOLD 50
#define TEMP_ADC_OPEN_THRESHOLD 4000

#define TEMP_MIN_VALID_C -40.0f
#define TEMP_MAX_VALID_C 150.0f

#define FAN_TEMP_ON_C 85.0f
#define FAN_TEMP_FULL_C 100.0f

#define FAN_MIN_DUTY 10.0f
#define FAN_MAX_DUTY 90.0f

#define AC_MULTIPLIER 2.0f

#endif // !FZ_CONFIG_H
